### ISSUE TITLE
error:0906D06C

### ISSUE THREAD

**Issue by Nocthan** [jfromaniello/selfsigned#27]
Guys, any ideas?

OS: Windows 10
Node.js version: node-v8.11.4-win-x64
node-forge version: 0.7.7-dev
selfsigned version: 1.10.3

Code:
```
var https = require('https');
var selfsigned = require('selfsigned');

var attrs = [{ name: 'commonName', value: 'contoso.com' }];
var pems = selfsigned.generate(attrs, { days: 365 });

https.createServer( { key:pems.public, cert:pems.cert },(req,res)=>
{
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World\n');

}).listen(443);
```

Result:
```
E:\forge_case\node-v8.11.4-win-x64>node.exe index.js
_tls_common.js:104
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:104:17)
    at Server (_tls_wrap.js:805:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at Object.<anonymous> (E:\forge_case\node-v8.11.4-win-x64\index.js:7:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Comment by jfromaniello** [comment]
this line doesn't look right:
```
https.createServer( { key:pems.public, cert:pems.cert },(req,res)=>

```
I think it should be
`key: pems.private`

**Comment by Nocthan** [comment]
You're right. 😅

[runs away shamefully]

**Comment by jfromaniello** [comment]
No problem, glad to help :)
